services:
  portainer:
    image: portainer/portainer-ce:2.27.1-alpine   # Prev: 2.23.0-alpine
    container_name: Portainer
    restart: unless-stopped
    ports:
      - 9000:9000
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Rome
    volumes:
      - ./portainer-volume:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
