services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.21.3-debian
    container_name: Uptime-Kuma
    restart: unless-stopped
    ports:
      - 3001:3001
    environment: 
      - TZ=Europe/Rome
    volumes:
      - ./uptime-kuma-volume:/app/data
      - /var/run/docker.sock:/var/run/docker.sock     # To enable connection to Docker engine and container monitoring
